print ("hello world")
print ("November")
print ("November2023-11-18")
print ("I broke my keys arrow left and right")
print ("I hope I can fix it ####")
print ("i need to poop")
print ("pr.py lesson2.py")
print ("file edit view go run ... you")
print ("endi_x@DASKTP-S537MEQ:~/python$")
print ("ediakomaliza")
line01 = "********************" # header / footer
line02 = "*                  *" # re-use
line03 = "*      Welcome     *"

# starts with a blank line
print('')
print(line01)
print(line02)
print(line03)
print(line02)
print(line01)
print ("hello world")
print ("endinako is giong to grade7 in 2 month scary!")
print ("i am thankfull for my grandma and famiy")
print ("i am about to sleep 20:48")
print ("10 more minutes until i sleep")
print ("my aunt and my grandma are fighting about a test paper so funny ")
print ("there are flower paddells on the table it is dirty")
print ("my grandma makes ginger but i don't like ginger")
print ("people say that my grandma ginger is nice ")
print ("i dont get what is the fuss about it")
print ("peraise the lord on my soul ")
print ("my praises lie water my enemys drown in it ")
print ("everything that has breath praise the lord")
print ("i am going to sleep bye bye")
print ("people are funny")
print ("endinako is my best friend")
print ("god is the only god in the universe")
print ("u are the best")